common:
  loggingLevel: 'info'
  saveLog: false
  workersPerProject: 1
  save_steps: 1
  sourceLanguage: 'ja'
  targetLanguage: 'zh-cn'

  skipH: false
  skipRetry: false
  retranslFail: true

  gpt.numPerRequestTranslate: 8
  gpt.streamOutputMode: false
  gpt.tooManyRequestsWaitTime: 60
  gpt.enhance_jailbreak: true
  gpt.change_prompt: 'no'
  gpt.prompt_content: ''

  gpt.restoreContextMode: true

  gpt.token_limit: 0
  gpt.transl_dropout: 0


plugin:
  filePlugin: file_galtransl_json
  textPlugins: []


proxy:
  enableProxy: false
  proxies:
    - address: http://localhost:9000


dictionary:
  defaultDictFolder: dict
  sortDict: true
  usePreDictInName: false
  usePostDictInName: false
  preDict:
    - pre-ero.txt
  gpt.dict:
    - gpt-dict.txt
    - gpt-general.txt
  postDict:
    - post-general.txt


backendSpecific:
  OpenAI-Compatible:
    tokens:
      - token: ''
        endpoint: ''
    rewriteModelName: ''

  SakuraLLM:
    endpoints:
      - 'http://localhost:11434'
    rewriteModelName: 'Galtransl-14B'


problemAnalyze:
  problemList:
    - 词频过高 # 重复大于20次
    - 标点错漏 # 标点符号多加或漏加
    - 丢失换行 # 缺少换行符，一般没事
    - 多加换行 # 换行符比原句多，可能导致溢出屏幕
    - 字典使用 # 没有按GPT字典要求翻译
    - 引入英文 # 本来没有英文，译文引入了英文
    # - 比日文长 # 比日文长1.3倍以上
    # - 残留日文 # 日文平假名片假名残留
