[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gtbridge"
version = "0.1.0"
requires-python = ">=3.7"
dependencies = []

[tool.setuptools]
packages = ["gtbridge"]
package-dir = {"gtbridge" = "."}
